version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      #- cluster.name=tcanter
      #- "ES_JAVA_OPTS=-Xms768m -Xmx768m"
    networks:
      - default
